# Generated by Django 5.1.7 on 2025-03-09 21:09

import django.db.models.deletion
import filer.fields.file
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0017_image__transparent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTSConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_model', models.CharField(default='F5-TTS', max_length=100)),
                ('configuration', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('prompt_text', models.TextField()),
                ('generated_text', models.TextField(blank=True)),
                ('reference_text', models.TextField(blank=True)),
                ('reference_audio', models.FileField(blank=True, null=True, upload_to='usage/reference/')),
                ('generated_audio', models.FileField(blank=True, null=True, upload_to='usage/generated/')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('reference_text', models.TextField(blank=True)),
                ('duration', models.FloatField(default=0.0)),
                ('is_default_speaker', models.BooleanField(default=False)),
                ('default_speed', models.FloatField(default=1.0)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('KM', 'Male (Kid)'), ('KF', 'Female (Kid)')], default='M', max_length=3)),
                ('language', models.CharField(default='th', max_length=128)),
                ('reference_audio', filer.fields.file.FilerFileField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_audio', to='filer.file')),
            ],
        ),
    ]
