# Generated by Django 5.1.7 on 2025-03-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('reference_text', models.TextField(blank=True)),
                ('reference_audio', models.FileField(upload_to='speakers/')),
            ],
        ),
        migrations.CreateModel(
            name='TTSConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_model', models.CharField(default='F5-TTS', max_length=100)),
                ('configuration', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('prompt_text', models.TextField()),
                ('generated_text', models.TextField(blank=True)),
                ('reference_text', models.TextField(blank=True)),
                ('reference_audio', models.FileField(blank=True, null=True, upload_to='usage/reference/')),
                ('generated_audio', models.FileField(blank=True, null=True, upload_to='usage/generated/')),
            ],
        ),
    ]
