# Generated by Django 5.1.7 on 2025-03-10 06:47

import uuid

import django.db.models.deletion
import filer.fields.file
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('filer', '0017_image__transparent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTSConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('Custom', 'Custom'), ('F5-TTS', 'F5-TTS')], default='Custom',
                                           max_length=256)),
                ('checkpoint', models.CharField(blank=True, max_length=256, null=True)),
                ('vocab', models.CharField(blank=True, max_length=256, null=True)),
                ('config', models.JSONField(blank=True, choices=[(
                                                                 '{"dim": 1024, "depth": 22, "heads": 16, "ff_mult": 2, "text_dim": 512, "conv_layers": 4}',
                                                                 'Default ({"dim": 1024, "depth": 22, "heads": 16, "ff_mult": 2, "text_dim": 512, "conv_layers": 4})'),
                                                                 (
                                                                 '{"dim": 768, "depth": 18, "heads": 12, "ff_mult": 2, "text_dim": 512, "conv_layers": 4}',
                                                                 'Small ({"dim": 768, "depth": 18, "heads": 12, "ff_mult": 2, "text_dim": 512, "conv_layers": 4})')],
                                            default='Default ({"dim": 1024, "depth": 22, "heads": 16, "ff_mult": 2, "text_dim": 512, "conv_layers": 4})',
                                            null=True)),
            ],
            options={
                'verbose_name': 'TTS Configuration',
                'verbose_name_plural': 'TTS Configurations',
            },
        ),
        migrations.CreateModel(
            name='ReferenceAudio',
            fields=[
                ('uuid',
                 models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(blank=True)),
                ('duration', models.FloatField(default=0.0)),
                ('audio', filer.fields.file.FilerFileField(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                           related_name='reference_audio', to='filer.file')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_id', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('default', models.BooleanField(default=False)),
                ('default_speed', models.FloatField(default=1.0)),
                ('gender', models.CharField(
                    choices=[('M', 'Male'), ('F', 'Female'), ('KM', 'Male (Kid)'), ('KF', 'Female (Kid)')], default='M',
                    max_length=3)),
                ('language', models.CharField(default='th', max_length=128)),
                ('reference', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                   to='tts.referenceaudio')),
            ],
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_text', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('custom_reference', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                          to='tts.referenceaudio')),
                ('enhanced_audio',
                 filer.fields.file.FilerFileField(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                  related_name='enhanced_audio', to='filer.file')),
                ('generated_audio',
                 filer.fields.file.FilerFileField(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                  related_name='generated_audio', to='filer.file')),
                ('speaker',
                 models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tts.speaker')),
            ],
        ),
    ]
