# Generated by Django 5.1.7 on 2025-03-10 07:21

import django.db.models.deletion
import filer.fields.file
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('filer', '0017_image__transparent'),
        ('tts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagelog',
            name='spectrogram',
            field=filer.fields.file.FilerFileField(editable=False, null=True,
                                                   on_delete=django.db.models.deletion.SET_NULL,
                                                   related_name='spectrogram', to='filer.file'),
        ),
        migrations.AlterField(
            model_name='usagelog',
            name='enhanced_audio',
            field=filer.fields.file.FilerFileField(editable=False, null=True,
                                                   on_delete=django.db.models.deletion.SET_NULL,
                                                   related_name='enhanced_audio', to='filer.file'),
        ),
        migrations.AlterField(
            model_name='usagelog',
            name='generated_audio',
            field=filer.fields.file.FilerFileField(editable=False, null=True,
                                                   on_delete=django.db.models.deletion.SET_NULL,
                                                   related_name='generated_audio', to='filer.file'),
        ),
    ]
