# Generated by Django 5.1.7 on 2025-03-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ttsconfiguration',
            options={'verbose_name': 'TTS Configuration', 'verbose_name_plural': 'TTS Configurations'},
        ),
        migrations.RenameField(
            model_name='ttsconfiguration',
            old_name='configuration',
            new_name='config',
        ),
        migrations.RemoveField(
            model_name='ttsconfiguration',
            name='current_model',
        ),
        migrations.AddField(
            model_name='ttsconfiguration',
            name='checkpoint',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='ttsconfiguration',
            name='model',
            field=models.CharField(choices=[('Custom', 'Custom'), ('F5-TTS', 'F5-TTS')], default='Custom', max_length=256),
        ),
        migrations.AddField(
            model_name='ttsconfiguration',
            name='vocab',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
