# Generated by Django 5.1.7 on 2025-03-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0002_alter_ttsconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttsconfiguration',
            name='config',
            field=models.JSONField(blank=True, choices=[('Default', [('dim', 1024), ('depth', 22), ('heads', 16), ('ff_mult', 2), ('text_dim', 512), ('conv_layers', 4)]), ('Small', [('dim', 768), ('depth', 18), ('heads', 12), ('ff_mult', 2), ('text_dim', 512), ('conv_layers', 4)])], default={'conv_layers': 4, 'depth': 22, 'dim': 1024, 'ff_mult': 2, 'heads': 16, 'text_dim': 512}, null=True),
        ),
    ]
