# Generated by Django 5.1.7 on 2025-03-10 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tts', '0003_alter_usagelog_custom_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagelog',
            name='custom_reference',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='tts.referenceaudio'),
        ),
        migrations.AlterField(
            model_name='usagelog',
            name='speaker',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='tts.speaker'),
        ),
    ]
