# Generated by Django 5.1.7 on 2025-03-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0003_alter_ttsconfiguration_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='speaker_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ttsconfiguration',
            name='config',
            field=models.JSONField(blank=True, choices=[('{"dim": 1024, "depth": 22, "heads": 16, "ff_mult": 2, "text_dim": 512, "conv_layers": 4}', 'Default ({"dim": 1024, "depth": 22, "heads": 16, "ff_mult": 2, "text_dim": 512, "conv_layers": 4})'), ('{"dim": 768, "depth": 18, "heads": 12, "ff_mult": 2, "text_dim": 512, "conv_layers": 4}', 'Small ({"dim": 768, "depth": 18, "heads": 12, "ff_mult": 2, "text_dim": 512, "conv_layers": 4})')], default='Default ({"dim": 1024, "depth": 22, "heads": 16, "ff_mult": 2, "text_dim": 512, "conv_layers": 4})', null=True),
        ),
    ]
