# Generated by Django 5.1.7 on 2025-03-09 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0004_speaker_speaker_id_alter_ttsconfiguration_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speaker',
            old_name='is_default_speaker',
            new_name='default',
        ),
    ]
